/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Fish Telemetry",
  "description": "fish",
  "userscripts": [
    {
      "url": "thetele.js"
    }
  ],
  "dynamicDisable": false,
  "enabledByDefault": true,
  "noTouchyRequired": true,
  "tags": [
    "danger"
  ]
};
export default manifest;
