/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "USB Anarchy mode",
  "description": "Connect any block into any input.",
  "credits": [
    {
      "name": "LilyMakesThings",
      "link": "https://scratch.mit.edu/users/LilyMakesThings/"
    },
    {
      "name": "pumpkinstuf"
    }
  ],
  "userscripts": [
    {
      "url": "anarchy.js"
    }
  ],
  "dynamicDisable": false,
  "enabledByDefault": false,
  "tags": [
    "danger"
  ]
};
export default manifest;
