/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Wingdings Everywhere🤯",
  "description": "Turn basically all text into Wingdings",
  "userstyles": [
    {
      "url": "wingdings.css"
    }
  ],
  "credits": [
    {
      "name": "pumpkinstuf",
      "link": "https://scratch.mit.edu/users/Pumpkinbunny/"
    }
  ],
  "tags": [
    "theme"
  ],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
