/* generated by pull.js */
const manifest = {
  "name": "Editor link fix",
  "description": "Fixes a Scratch bug that slows down project loading if the editor is opened from a link.",
  "credits": [
    {
      "name": "Tacodiva",
      "link": "https://scratch.mit.edu/users/Tacodiva7729/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "beta"
  ],
  "enabledByDefault": false
};
export default manifest;
