/* generated by pull.js */
const manifest = {
  "name": "Expandable search bar",
  "description": "Makes the search bar in the navigation bar wider when it's focused.",
  "credits": [
    {
      "name": "CST1229",
      "link": "https://github.com/cst1229"
    }
  ],
  "userscripts": [],
  "dynamicDisable": true,
  "tags": [
    "beta"
  ],
  "enabledByDefault": false
};
export default manifest;
