/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Disable super secret settings button",
  "description": "Removes the super secret settings button from the menu bar.",
  "userstyles": [
    {
      "url": "nomoresupersettings.css"
    }
  ],
  "tags": [
    "danger"
  ],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
