/* generated by pull.js */
const manifest = {
  "name": "Emoji picker for comments",
  "description": "Adds a button to insert emojis to comments on the website.",
  "credits": [
    {
      "name": "CST1229",
      "link": "https://github.com/CST1229"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "userstyle.css"
    }
  ],
  "dynamicDisable": true,
  "tags": [
    "beta"
  ],
  "enabledByDefault": false
};
export default manifest;
